import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  notFound: {
    display: "flex",
    minHeight: "100svh",
    alignItems: "center",
    justifyContent: "center",
    padding: "calc(var(--spacing) * 6)",
  },
  centered: { textAlign: "center" },
  homeLink: {
    marginTop: "calc(var(--spacing) * 2)",
    display: "inline-block",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    color: "var(--primary)",
    textDecorationLine: {
      default: null,
      "@media (hover: hover)": { ":hover": "underline" },
    },
  },
  appShell: {
    display: "flex",
    minHeight: "100svh",
    flexDirection: "column",
  },
  leftPanel: {
    position: "relative",
    zIndex: "10",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: "calc(var(--spacing) * 6)",
    paddingBlock: "calc(var(--spacing) * 12)",
  },
  themeToggle: {
    position: "absolute",
    top: "calc(var(--spacing) * 4)",
    right: "calc(var(--spacing) * 4)",
  },
  icon: {
    width: "calc(var(--spacing) * 4)",
    height: "calc(var(--spacing) * 4)",
  },
  formColumn: {
    display: "flex",
    width: "100%",
    maxWidth: "var(--container-md)",
    flexDirection: "column",
    gap: "calc(var(--spacing) * 6)",
  },
  title: {
    fontSize: "var(--text-2xl)",
    lineHeight: "var(--tw-leading,var(--text-2xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-tracking": "var(--tracking-tight)",
    letterSpacing: "var(--tracking-tight)",
  },
  subtitle: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
  },
  form: {
    display: "flex",
    gap: "calc(var(--spacing) * 2)",
  },
  inputWrap: {
    position: "relative",
    flex: "1",
  },
  repositoryInput: {
    borderColor: "var(--chart-3)",
    paddingRight: "calc(var(--spacing) * 9)",
    color: "var(--chart-1)",
  },
  pasteButton: {
    position: "absolute",
    top: "50%",
    right: "calc(var(--spacing) * 1.5)",
    "--tw-translate-y": "calc(calc(1 / 2 * 100%) * -1)",
    translate: "var(--tw-translate-x) var(--tw-translate-y)",
    color: "var(--muted-foreground)",
  },
  pasteIcon: {
    width: "calc(var(--spacing) * 3.5)",
    height: "calc(var(--spacing) * 3.5)",
  },
  settingsToggle: {
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing) * 1.5)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    color: "var(--muted-foreground)",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  settingsChevron: {
    width: "calc(var(--spacing) * 3)",
    height: "calc(var(--spacing) * 3)",
    transitionProperty: "transform,translate,scale,rotate",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  settingsFields: {
    marginTop: "calc(var(--spacing) * 3)",
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing) * 3)",
  },
  settingRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  labelText: {
    fontSize: "var(--text-xs)",
    lineHeight: "var(--text-xs--line-height)",
    "--tw-leading": null,
  },
  smallText: {
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
  },
  smallMuted: {
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    color: "var(--muted-foreground)",
  },
  formatGroup: {
    display: "flex",
  },
  formatSelected: {
    borderColor: "var(--foreground)",
    backgroundColor: "var(--foreground)",
    color: "var(--background)",
  },
  formatUnselected: {
    borderColor: "var(--border)",
    color: "var(--muted-foreground)",
  },
  starPanel: {
    position: "relative",
    minHeight: "0",
    flex: "1",
    overflow: "hidden",
  },
  dialogOverflow: {
    overflow: "hidden",
  },
  subpath: {
    fontFamily: "JetBrains Mono Variable,monospace",
    wordBreak: "break-all",
    color: "var(--foreground)",
  },
  repoName: {
    fontFamily: "JetBrains Mono Variable,monospace",
    color: "var(--foreground)",
  },
  errorBox: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--destructive)",
    padding: "calc(var(--spacing) * 3)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
  },
  dismissError: {
    marginLeft: "calc(var(--spacing) * 2)",
  },
  smallIcon: {
    width: "calc(var(--spacing) * 3)",
    height: "calc(var(--spacing) * 3)",
  },
  buttonBase: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#0000",
    backgroundClip: "padding-box",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    WebkitUserSelect: "none",
    userSelect: "none",
  },
  buttonDefault: {
    backgroundColor: "var(--primary)",
    color: "var(--primary-foreground)",
  },
  buttonOutline: {
    borderColor: "var(--border)",
    backgroundColor: "var(--background)",
  },
  buttonSecondary: {
    backgroundColor: "var(--secondary)",
    color: "var(--secondary-foreground)",
  },
  buttonGhost: {},
  buttonDestructive: {
    backgroundColor: "var(--destructive)",
  },
  buttonLink: {
    color: "var(--primary)",
    textUnderlineOffset: "4px",
  },
  buttonSizeDefault: {
    height: "calc(var(--spacing) * 8)",
    gap: "calc(var(--spacing) * 1.5)",
    paddingInline: "calc(var(--spacing) * 2.5)",
  },
  buttonSizeXs: {
    height: "calc(var(--spacing) * 6)",
    gap: "var(--spacing)",
    borderRadius: "0",
    paddingInline: "calc(var(--spacing) * 2)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
  },
  buttonSizeSm: {
    height: "calc(var(--spacing) * 7)",
    gap: "var(--spacing)",
    borderRadius: "0",
    paddingInline: "calc(var(--spacing) * 2.5)",
  },
  buttonSizeLg: {
    height: "calc(var(--spacing) * 9)",
    gap: "calc(var(--spacing) * 1.5)",
    paddingInline: "calc(var(--spacing) * 2.5)",
  },
  buttonSizeIcon: {
    width: "calc(var(--spacing) * 8)",
    height: "calc(var(--spacing) * 8)",
  },
  buttonSizeIconXs: {
    width: "calc(var(--spacing) * 6)",
    height: "calc(var(--spacing) * 6)",
    borderRadius: "0",
  },
  buttonSizeIconSm: {
    width: "calc(var(--spacing) * 7)",
    height: "calc(var(--spacing) * 7)",
    borderRadius: "0",
  },
  buttonSizeIconLg: {
    width: "calc(var(--spacing) * 9)",
    height: "calc(var(--spacing) * 9)",
  },
  inputBase: {
    height: "calc(var(--spacing) * 8)",
    width: "100%",
    minWidth: "0",
    borderRadius: "0",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--input)",
    backgroundColor: "#0000",
    paddingInline: "calc(var(--spacing) * 2.5)",
    paddingBlock: "var(--spacing)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
  },
  labelBase: {
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing) * 2)",
    fontSize: "var(--text-xs)",
    lineHeight: "1",
    "--tw-leading": "1",
    WebkitUserSelect: "none",
    userSelect: "none",
  },
  switchBase: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "2147483647px",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#0000",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
  },
  switchThumb: {
    pointerEvents: "none",
    display: "block",
    borderRadius: "2147483647px",
    backgroundColor: "var(--background)",
    "--tw-ring-shadow":
      "var(--tw-ring-inset,) 0 0 0 calc(0px + var(--tw-ring-offset-width)) var(--tw-ring-color,currentcolor)",
    boxShadow:
      "var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow)",
    transitionProperty: "transform,translate,scale,rotate",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  dialogOverlay: {
    position: "fixed",
    inset: "0",
    zIndex: "50",
    backgroundColor: "#0000001a",
    "--tw-duration": ".1s",
    transitionDuration: ".1s",
  },
  dialogContent: {
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "50",
    display: "grid",
    width: "calc(100% - 2rem)",
    "--tw-translate-x": "calc(calc(1 / 2 * 100%) * -1)",
    translate: "var(--tw-translate-x) var(--tw-translate-y)",
    "--tw-translate-y": "calc(calc(1 / 2 * 100%) * -1)",
    gap: "calc(var(--spacing) * 4)",
    overflow: "hidden",
    borderRadius: "0",
    backgroundColor: "var(--popover)",
    padding: "calc(var(--spacing) * 4)",
    color: "var(--popover-foreground)",
    "--tw-ring-shadow":
      "var(--tw-ring-inset,) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color,currentcolor)",
    boxShadow:
      "var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow)",
    "--tw-ring-color": "var(--foreground)",
    "--tw-duration": ".1s",
    transitionDuration: ".1s",
    "--tw-outline-style": "none",
    outlineStyle: "none",
  },
  dialogHeader: {
    display: "grid",
    gridTemplateRows: "auto 1fr",
    placeItems: "center",
    gap: "calc(var(--spacing) * 1.5)",
    textAlign: "center",
  },
  dialogFooter: {
    display: "flex",
    flexDirection: "column-reverse",
    gap: "calc(var(--spacing) * 2)",
  },
  dialogMedia: {
    marginBottom: "calc(var(--spacing) * 2)",
    display: "inline-flex",
    width: "calc(var(--spacing) * 10)",
    height: "calc(var(--spacing) * 10)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0",
    backgroundColor: "var(--muted)",
  },
  dialogTitle: {
    fontFamily: "var(--font-mono)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
  },
  dialogDescription: {
    fontSize: "var(--text-xs)",
    lineHeight: "var(--leading-relaxed)",
    textWrap: "balance",
    color: "var(--muted-foreground)",
  },
  starfieldCanvas: {
    position: "absolute",
    inset: "0",
    height: "100%",
    width: "100%",
  },
  formatButton: {
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    paddingInline: "calc(var(--spacing) * 4)",
    paddingBlock: "calc(var(--spacing) * 1.5)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  formatOverlap: {
    marginLeft: "-1px",
  },
})

export const classNames = {
  appShell: `${stylex.props(styles.appShell).className ?? ""} dgit-appShell`,
  leftPanel: `${stylex.props(styles.leftPanel).className ?? ""} dgit-leftPanel`,
  themeToggle: `${stylex.props(styles.themeToggle).className ?? ""} dgit-themeToggle`,
  icon: `${stylex.props(styles.icon).className ?? ""} dgit-icon`,
  formColumn: `${stylex.props(styles.formColumn).className ?? ""} dgit-formColumn`,
  title: `${stylex.props(styles.title).className ?? ""} dgit-title`,
  subtitle: `${stylex.props(styles.subtitle).className ?? ""} dgit-subtitle`,
  form: `${stylex.props(styles.form).className ?? ""} dgit-form`,
  inputWrap: `${stylex.props(styles.inputWrap).className ?? ""} dgit-inputWrap`,
  repositoryInput: `${stylex.props(styles.repositoryInput).className ?? ""} dgit-repositoryInput`,
  pasteButton: `${stylex.props(styles.pasteButton).className ?? ""} dgit-pasteButton`,
  pasteIcon: `${stylex.props(styles.pasteIcon).className ?? ""} dgit-pasteIcon`,
  settingsToggle: `${stylex.props(styles.settingsToggle).className ?? ""} dgit-settingsToggle`,
  settingsChevron: `${stylex.props(styles.settingsChevron).className ?? ""} dgit-settingsChevron`,
  settingsFields: `${stylex.props(styles.settingsFields).className ?? ""} dgit-settingsFields`,
  settingRow: `${stylex.props(styles.settingRow).className ?? ""} dgit-settingRow`,
  smallText: `${stylex.props(styles.smallText).className ?? ""} dgit-smallText`,
  smallMuted: `${stylex.props(styles.smallMuted).className ?? ""} dgit-smallMuted`,
  formatGroup: `${stylex.props(styles.formatGroup).className ?? ""} dgit-formatGroup`,
  formatSelected: `${stylex.props(styles.formatSelected).className ?? ""} dgit-formatSelected`,
  formatUnselected: `${stylex.props(styles.formatUnselected).className ?? ""} dgit-formatUnselected`,
  starPanel: `${stylex.props(styles.starPanel).className ?? ""} dgit-starPanel`,
  dialogOverflow: `${stylex.props(styles.dialogOverflow).className ?? ""} dgit-dialogOverflow`,
  subpath: `${stylex.props(styles.subpath).className ?? ""} dgit-subpath`,
  repoName: `${stylex.props(styles.repoName).className ?? ""} dgit-repoName`,
  errorBox: `${stylex.props(styles.errorBox).className ?? ""} dgit-errorBox`,
  dismissError: `${stylex.props(styles.dismissError).className ?? ""} dgit-dismissError`,
  smallIcon: `${stylex.props(styles.smallIcon).className ?? ""} dgit-smallIcon`,
  buttonBase: `${stylex.props(styles.buttonBase).className ?? ""} dgit-buttonBase`,
  buttonDefault: `${stylex.props(styles.buttonDefault).className ?? ""} dgit-buttonDefault`,
  buttonOutline: `${stylex.props(styles.buttonOutline).className ?? ""} dgit-buttonOutline`,
  buttonSecondary: `${stylex.props(styles.buttonSecondary).className ?? ""} dgit-buttonSecondary`,
  buttonGhost: `${stylex.props(styles.buttonGhost).className ?? ""} dgit-buttonGhost`,
  buttonDestructive: `${stylex.props(styles.buttonDestructive).className ?? ""} dgit-buttonDestructive`,
  buttonLink: `${stylex.props(styles.buttonLink).className ?? ""} dgit-buttonLink`,
  buttonSizeDefault: `${stylex.props(styles.buttonSizeDefault).className ?? ""} dgit-buttonSizeDefault`,
  buttonSizeXs: `${stylex.props(styles.buttonSizeXs).className ?? ""} dgit-buttonSizeXs`,
  buttonSizeSm: `${stylex.props(styles.buttonSizeSm).className ?? ""} dgit-buttonSizeSm`,
  buttonSizeLg: `${stylex.props(styles.buttonSizeLg).className ?? ""} dgit-buttonSizeLg`,
  buttonSizeIcon: `${stylex.props(styles.buttonSizeIcon).className ?? ""} dgit-buttonSizeIcon`,
  buttonSizeIconXs: `${stylex.props(styles.buttonSizeIconXs).className ?? ""} dgit-buttonSizeIconXs`,
  buttonSizeIconSm: `${stylex.props(styles.buttonSizeIconSm).className ?? ""} dgit-buttonSizeIconSm`,
  buttonSizeIconLg: `${stylex.props(styles.buttonSizeIconLg).className ?? ""} dgit-buttonSizeIconLg`,
  inputBase: `${stylex.props(styles.inputBase).className ?? ""} dgit-inputBase`,
  labelBase: `${stylex.props(styles.labelBase).className ?? ""} dgit-labelBase`,
  switchBase: `${stylex.props(styles.switchBase).className ?? ""} dgit-switchBase`,
  switchThumb: `${stylex.props(styles.switchThumb).className ?? ""} dgit-switchThumb`,
  dialogOverlay: `${stylex.props(styles.dialogOverlay).className ?? ""} dgit-dialogOverlay`,
  dialogContent: `${stylex.props(styles.dialogContent).className ?? ""} dgit-dialogContent`,
  dialogHeader: `${stylex.props(styles.dialogHeader).className ?? ""} dgit-dialogHeader`,
  dialogFooter: `${stylex.props(styles.dialogFooter).className ?? ""} dgit-dialogFooter`,
  dialogMedia: `${stylex.props(styles.dialogMedia).className ?? ""} dgit-dialogMedia`,
  dialogTitle: `${stylex.props(styles.dialogTitle).className ?? ""} dgit-dialogTitle`,
  dialogDescription: `${stylex.props(styles.dialogDescription).className ?? ""} dgit-dialogDescription`,
  starfieldCanvas: `${stylex.props(styles.starfieldCanvas).className ?? ""} dgit-starfieldCanvas`,
  formatButton: `${stylex.props(styles.formatButton).className ?? ""} dgit-formatButton`,
  formatOverlap: `${stylex.props(styles.formatOverlap).className ?? ""} dgit-formatOverlap`,
}
